### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Lrs121** [Lrs121/meta-wren-hybris#1]
- [ ] Get a 5.1.1 system image copy
- [ ] Adapt patches to wren kernel
- [ ] Grep for instances of sparrow and replace
- [ ] Find testers

**Comment by Lrs121** [comment]
REFS:
https://github.com/HostZero/android_device_asus_wren/tree/android-6.0
http://forum.xda-developers.com/zenwatch-2/help/wip-compiling-twrp-wi502q-wren-device-t3341435
